### PR TITLE
Removes removed item from selection, Fixed out of array bound bug

### PR DESCRIPTION
**Pull request by tejainece**
I have fixed an out of array bounds bug in _valueToSelection and also implemented a way to remove items in selection that are removed from the selector.

### CODE REVIEW

**Comment by zoechi** [comment]
Hi tejainece, thanks a lot for your contribution!
I'm quite under pressure currently and deprived of sleep. I hope you don't mind if it takes a day until I can take a closer look.

**Comment by tejainece** [comment]
Sure. Take your time. Also, let me know if you want it implemented it any other way.

**Comment by zoechi** [comment]
How did you use polymer-selector to run into this bug/limitations? It might make sense to report this to the JavaScript polymer-elements project too where we ported these elements from.

**Comment by tejainece** [comment]
This involves one bug and one limitation.
Bug: Out of array bounds
Steps to reproduce:
1) Select the last element
2) Remove any element in the list
3) It will produce an error because items are not selected based on item but based on index
Fix:
1) Using mutation, I am removing item from the selection if it is removed from the item list.

Note: There is also an associated limitation here which is not fixed by this pull request. Since the items are selected by index, when you remove an element, new item is selected based on the index and the item you really wanted to select would be deselected.

Fix for this yet unfixed bug:
1) Track selection by item instead of tracking it by index.

**Comment by zoechi** [comment]
Thanks for you super-fast reply :-)

I wasn't able to reproduce with this example 
https://github.com/zoechi/polymer_elements_playground/blob/master/web/polymer_selection.html
(derived from https://github.com/ErikGrimes/polymer_elements/blob/master/example/polymer_selection.html)
In this example the selection is done `by item`.

I modified it so that initially the item 'Blue' (of `Red`, `Green`, `Blue`) is selected and if you click `Red` or `Green` the clicked item gets remove.
I clicked `Green` it got removed and `Blue` was moved to 2nd pos and still selected. 

Do you have some actual example code to reproduce?

I ported a lot of the elements but haven't had much chance to use them myself yet. I didn't port polymer-selection/polymer-selector but did a lot of debugging and some updates so I know it well.

As far as I remember `select by index` is done when `by item` is not possible but I don't know now what could prevent `select by item`.

**Pull request closed without merging**
